// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VueJsTest.Models;

namespace VueJsTest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190616145341_posts")]
    partial class posts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("VueJsTest.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("VueJsTest.Models.PostRubric", b =>
                {
                    b.Property<int>("PostId");

                    b.Property<int>("RubricId");

                    b.HasKey("PostId", "RubricId");

                    b.HasIndex("RubricId");

                    b.ToTable("PostRubric");
                });

            modelBuilder.Entity("VueJsTest.Models.Rubric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Rubrics");
                });

            modelBuilder.Entity("VueJsTest.Models.PostRubric", b =>
                {
                    b.HasOne("VueJsTest.Models.Post", "Post")
                        .WithMany("PostRubrics")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VueJsTest.Models.Rubric", "Rubric")
                        .WithMany("PostRubrics")
                        .HasForeignKey("RubricId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
